version: '3.8'

services:
  check_network_policies:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8945:8945"
    volumes:
      # - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - check_network_policies
    privileged: true 

networks:
  check_network_policies:
    driver: bridge
